services:
  ldap:
    container_name: ldap
    image: dcm4che/slapd-dcm4chee:2.6.6-32.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      STORAGE_DIR: /storage/fs1
    restart: unless-stopped
    ports:
      - "${LDAP_PORT}:389"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/mesy-reports/dcm4chee/ldap:/var/lib/openldap/openldap-data
      - /var/local/mesy-reports/dcm4chee/slapd.d:/etc/openldap/slapd.d
  db:
    container_name: db
    image: dcm4che/postgres-dcm4chee:16.2-32
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/mesy-reports/dcm4chee/db:/var/lib/postgresql/data
  arc:
    container_name: arc
    image: dcm4che/dcm4chee-arc-psql:5.32.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: unless-stopped
    depends_on:
      - db
      - ldap
    ports:
      - "${ARC_PORT8080}:8080"
      - "${ARC_PORT8443}:8443"
      - "${ARC_PORT9990}:9990"
      - "${ARC_PORT11112}:11112"
      - "${ARC_PORT2575}:2575"
      - "${ARC_PORT9993}:9993"
      - "${ARC_PORT2672}:2762"
      - "${ARC_PORT12575}:12575"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: ${DB_PW}
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      WILDFLY_CHOWN: /storage
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/mesy-reports/dcm4chee/arc/wildfly:/opt/wildfly/standalone
      - /var/local/mesy-reports/dcm4chee/arc/storage:/storage
###################################
  reportsdb:
    container_name: reportsdb
    image: mysql:8.0.23
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      MYSQL_ROOT_PASSWORD: ${DB_PW}
    volumes:
     - /var/local/mesy-reports/mesy/reportsdb:/var/lib/mysql
  reportsapi:
    container_name: reportsapi
    image: mesys.azurecr.io/mesys-api-reports:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
    ports:
      - "${API_80}:8080"
      - "${API_443}:8081"
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  yourhealthapi:
    container_name: yourhealthapi
    image: mesys.azurecr.io/mesys-api-yourhealth:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
    ports:
      - "${YHAPI_80}:8080"
      - "${YHAPI_443}:8081"
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  gworchestrator:
    container_name: gworchestrator
    user: root
    image: mesys.azurecr.io/mesys-gw-orchestrator:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - reportsapi
    volumes:
     - /var/local/mesy-reports/mesy/gworchestrator:/app/Config
    environment:
      ROUTING_HOST: "https://gworchestrator"
      ROUTING_PORT: "8081"
      #ATTACHEDSERVICE_HOST: "gworchestrator"
      #ATTACHEDSERVICE_PORT: "5110"
      CAROUSELSERVICE_HOST: "mscarousel"
      CAROUSELSERVICE_PORT: "8080"
      CLIENTSERVICE_HOST: "msclient"
      CLIENTSERVICE_PORT: "8080"
      DEPARTMENTSERVICE_HOST: "msdepartment"
      DEPARTMENTSERVICE_PORT: "8080"
      IDENTITYSERVICE_HOST: "msidentity"
      IDENTITYSERVICE_PORT: "8080"
      INSTITUTIONSERVICE_HOST: "msinstitution"
      INSTITUTIONSERVICE_PORT: "8080"
      INSTITUTIONTAGSERVICE_HOST: "msinstitutiontag"
      INSTITUTIONTAGSERVICE_PORT: "8080"
      #LOGGERSERVICE_HOST: "gworchestrator"
      #LOGGERSERVICE_PORT: "5180"
      PATIENTSERVICE_HOST: "mspatient"
      PATIENTSERVICE_PORT: "8080"
      REPORTSERVICE_HOST: "msreport"
      REPORTSERVICE_PORT: "8080"
      REPORTTEMPLATESERVICE_HOST: "msreporttemplate"
      REPORTTEMPLATESERVICE_PORT: "8080"
      STATIONSERVICE_HOST: "msstation"
      STATIONSERVICE_PORT: "8080"
      STUDYSERVICE_HOST: "msstudy"
      STUDYSERVICE_PORT: "8080"
      #STUDYSTEPSERVICE_HOST: "gworchestrator"
      #STUDYSTEPSERVICE_PORT: "5260"
      STUDYVIEWERSERVICE_HOST: "msstudyviewer"
      STUDYVIEWERSERVICE_PORT: "8080"
      SYSTEMCONFIGURATIONSERVICE_HOST: "mssystemconfiguration"
      SYSTEMCONFIGURATIONSERVICE_PORT: "8080"
      SYSTEMROLSERVICE_HOST: "mssystemrol"
      SYSTEMROLSERVICE_PORT: "8080"
      USERSERVICE_HOST: "msuser"
      USERSERVICE_PORT: "8080"
      WORKERSERVICE_HOST: "msworker"
      WORKERSERVICE_PORT: "8080"
      LICENSESERVICE_HOST: "mslicense"
      LICENSESERVICE_PORT: "8080"
      TZ: "America/Argentina/Buenos_Aires"
  msidentity:
    container_name: msidentity
    image: mesys.azurecr.io/mesys-ms-identity:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  mscarousel:
    container_name: mscarousel
    image: mesys.azurecr.io/mesys-ms-carousel:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      #- msidentity
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msclient:
    container_name: msclient
    image: mesys.azurecr.io/mesys-ms-client:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - mscarousel
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msdepartment:
    container_name: msdepartment
    image: mesys.azurecr.io/mesys-ms-department:latest
    restart: unless-stopped
    ports:
      - "8089:8080"
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msclient
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      TZ: "America/Argentina/Buenos_Aires"
  msinstitution:
    container_name: msinstitution
    image: mesys.azurecr.io/mesys-ms-institution:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msdepartment
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msinstitutiontag:
    container_name: msinstitutiontag
    image: mesys.azurecr.io/mesys-ms-institutiontag:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msinstitution
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msmailing:
    container_name: msmailing
    image: mesys.azurecr.io/mesys-ms-mailing:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msinstitutiontag
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  mspatient:
    container_name: mspatient
    image: mesys.azurecr.io/mesys-ms-patient:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msinstitutiontag
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msreport:
    container_name: msreport
    image: mesys.azurecr.io/mesys-ms-report:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - mspatient
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msreporttemplate:
    container_name: msreporttemplate
    image: mesys.azurecr.io/mesys-ms-reporttemplate:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msreport
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msstation:
    container_name: msstation
    image: mesys.azurecr.io/mesys-ms-station:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msreporttemplate
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msstudy:
    container_name: msstudy
    image: mesys.azurecr.io/mesys-ms-study:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msstation
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msstudystep:
    container_name: msstudystep
    image: mesys.azurecr.io/mesys-ms-studystep:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msstation
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msstudyviewer:
    container_name: msstudyviewer
    image: mesys.azurecr.io/mesys-ms-studyviewer:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msstudy
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  mssystemconfiguration:
    container_name: mssystemconfiguration
    image: mesys.azurecr.io/mesys-ms-systemconfiguration:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msstudyviewer
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  mssystemrol:
    container_name: mssystemrol
    image: mesys.azurecr.io/mesys-ms-systemrol:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - mssystemconfiguration
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msuser:
    container_name: msuser
    image: mesys.azurecr.io/mesys-ms-user:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - mssystemrol
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  msworker:
    container_name: msworker
    image: mesys.azurecr.io/mesys-ms-worker:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      #- msuser
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
  mslicense:
    container_name: mslicense
    user: root
    image: mesys.azurecr.io/mesys-ms-license:latest
    restart: unless-stopped
    volumes:
     - /var/local/mesy-reports/mesy/api/:/app/license
    depends_on:
      - reportsdb
      - gworchestrator
      - reportsapi
      - msworker
    environment:
      DBSERVER: "reportsdb"
      DBPORT: "3306"
      DBPASS: ${DB_PW}
      ROUTERURI: "http://gworchestrator:8080"
      TZ: "America/Argentina/Buenos_Aires"
#############################################
  worker:
    container_name: worker
    image: mesys.azurecr.io/mesys-wk-dcm4chee-v5x32:latest
    restart: unless-stopped
    depends_on:
      - reportsdb
      - msworker
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      WORKERNAME: Servidor Demo
      APIURI: http://reportsapi:8080
      PACSSERVER: db
      PACSPORT: 5432
      PACSDB: pacsdb
      PACSUSER: pacs
      PACSPASS: ${DB_PW}
  adminweb:
    container_name: adminweb
    image: mesys.azurecr.io/mesys-frontend:latest
    restart: unless-stopped
    ports:
      - "${REPORTS_PORT80}:80"
      - "${REPORTS_PORT443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  yourhealthweb:
    container_name: yourhealthweb
    image: mesys.azurecr.io/mesys-pp-frontend:latest
    restart: unless-stopped
    ports:
      - "${YH_PORT80}:80"
      - "${YH_PORT443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#################################
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    container_name: placaxtunnel
    network_mode: "host"
  ohif:
    container_name: ohif
    image: alejovac/mesys-ohif-viewer:3.9.3
    restart: unless-stopped
    ports:
      - "${OHIF_80}:80"
    environment:
      NODE_ENV: "production"
      PUBLIC_URL: "/ohif/"
    volumes:
      - /var/local/mesy-reports/ohif/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - /var/local/mesy-reports/ohif/app-config.js:/usr/share/nginx/html/app-config.js
  ohiflocal:
    container_name: ohiflocal
    image: alejovac/mesys-ohifl-viewer:3.9.3
    restart: unless-stopped
    ports:
      - "${OHIF_Local}:80"
    environment:
      NODE_ENV: "production"
      PUBLIC_URL: "/ohifl/"
    volumes:
      - /var/local/mesy-reports/ohif/nginx-local.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - /var/local/mesy-reports/ohif/app-config-local.js:/usr/share/nginx/html/app-config.js
  oviyam:
    container_name: oviyam
    image:  postar/oviyam:1.0.4
    restart: unless-stopped
    depends_on:
      - arc
    ports:
      - "${OVIYAM_8080}:8080"
      - "${OVIYAM_1025}:1025"
    volumes:
      - /var/local/mesy-reports/oviyam:/usr/local/tomcat/work
networks:
  default:
      name: dcm4chee_default
      driver: bridge
      ipam:
        config:
          - subnet: 172.20.0.0/24
